### PR TITLE
Fix incremental update option Chinese translate

### PR DESCRIPTION
**Pull request by yukkodesu**

### CODE REVIEW

**Comment by jhonboy121** [comment]
What do you say @JohnsonRan

**Comment by JohnsonRan** [comment]
> What do you say @JohnsonRan

Ye,it was my mistake. merge it

**Comment by yukkodesu** [comment]
make 4 commits into 2
more elegant

**Comment by jhonboy121** [comment]
@yukkodesu squash those commits into two and force push

**Comment by JohnsonRan** [comment]
> @yukkodesu squash those commits into two and force push

I already told him to do so.and already two

**Pull request merged**
